# Server configuration
server:
  port: 8088
  # servlet:
  #  context-path: /api/v1

api:
  prefix: /api/v1
# Datasource configuration
spring:
  datasource:
    url: jdbc:mariadb://100.102.83.94:3306/insurtech
    username: root
    password: insurtech
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Prevents SQL statements from being split across multiple lines
#  logging:
#    level:
#      org.hibernate.SQL: debug  # Logs SQL queries at the debug level
#      org.hibernate.type.descriptor.sql.BasicBinder: trace  # Logs SQL parameters in the same line
#    pattern:
#      console: "%d{yyyy-MM-dd HH:mm:ss} - [%level] - %logger{36} - %msg%n"  # Log pattern with timestamp and concise formatting

  multipart:
    max-file-size: 10MB      # Giới hạn kích thước tệp tối đa (có thể thay đổi theo nhu cầu)
    max-request-size: 10MB    # Giới hạn kích thước toàn bộ yêu cầu (bao gồm cả các tệp)

jwt:
  expiration: 604800 # 1 day
  secretKey: KYbIMbDQ2deGncAVp4nyxlr8eJxqDwaQzWE+HXHoHvk=

minio:
  url: http://100.102.83.94:9000
  access-key: yhcHjshvyfEv8nnBPBDp
  secret-key: FhgncVHyTETijuemomk3LqekPsq8UI8kqmE4NPVh
  bucket:
    name: insurtech
