# Server configuration
server:
  port: 8088
  # servlet:
  #  context-path: /api/v1

api:
  prefix: /api/v1
# Datasource configuration
spring:
  datasource:
    url: jdbc:mariadb://100.102.83.94:3306/insurtech
    username: root
    password: insurtech
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: 86400 # 1 day
  secretKey: src/main/resources/keys/token_key.key
